### ISSUE TITLE
Recent versions of pyjwt break the package

### ISSUE THREAD

**Issue by sitic** [wikimedia/MediaWiki-OAuth#13]
When using `pip install mwoauth` the most recent version of PyJWT gets installed:
```
$ pip install mwoauth
$ pip freeze
PyJWT==0.4.1
mwoauth==0.2.3
oauthlib==0.7.2
requests==2.5.1
requests-oauthlib==0.4.2
```

This breaks the example from the README
```
$ python test.py
Point your browser to: X
Response query string: X
AccessToken(key='X', secret='X')
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    identity = handshaker.identify(access_token)
  File "/data/project/find-and-replace/.virtualenvs/test/local/lib/python2.7/site-packages/mwoauth/handshaker.py", line 100, in identify
    leeway=leeway)
  File "/data/project/find-and-replace/.virtualenvs/test/local/lib/python2.7/site-packages/mwoauth/functions.py", line 226, in identify
    consumer_token.secret, False)
  File "/data/project/find-and-replace/.virtualenvs/test/local/lib/python2.7/site-packages/jwt/__init__.py", line 399, in verify_signature
    raise InvalidAudienceError('Invalid audience')
jwt.InvalidAudienceError: Invalid audience
```

Using PyJWT version 0.2.1 as in `requirements.txt` fixes the problem, the version of PyJWT should be specified in `setup.py` to fix this.

Best wishes and thanks

**Comment by yuvipanda** [comment]
Yup, this just bit me as well. Paging the awesome @halfak
